### ISSUE TITLE
Make attribute list unordered.

### ISSUE THREAD

**Issue by fisx** [bgamari/html-parse#3]
```haskell
TagOpen !TagName [Attr]
```

would you accept a PR that changes this to:

```haskell
TagOpen !TagName (Set Attr)
```

**Comment by bgamari** [comment]
Hmm; honestly I'm a bit concerned about the performance impact that this might have since `Set` inserts must rebalance which involves both more computation and significantly more allocation. However, considering that most elements only have a few attributes the difference may be negligible.

In other words: I'm rather undecided but feel free to convince me we benchmark numbers.

**Comment by fisx** [comment]
Ok, you have a good point.  (It's not a high enough priority for me, so I close this until I change my mind and come back with some benchmarks.  Thanks for the feedback!  :-)
